version: "3"
services:
  selenium_chrome:
    network_mode: "host"
    image: "selenium/${SELENIUM_IMAGE:-standalone-chrome-debug}"
    volumes:
      - "/dev/shm:/dev/shm"
  selenium_firefox:
    network_mode: "host"
    image: "selenium/${SELENIUM_IMAGE:-standalone-firefox-debug}"
    volumes:
      - "/dev/shm:/dev/shm"
    environment:
      - SE_OPTS=-port 4445
